### ISSUE TITLE
Error on evil theme

### ISSUE THREAD

**Issue by augustocdias** [startup-nvim/startup.nvim#12]
When using the evil theme, I'm getting the following error:

```
E5113: Error while calling lua chunk: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_count'
        ...pack/packer/start/startup.nvim/lua/startup/functions.lua:23: in function 'packer_plugins'
        ...ck/packer/start/startup.nvim/lua/startup/themes/evil.lua:89: in main chunk
        [C]: in function 'require'
        /Users/augusto/.config/nvim/lua/theme.lua:49: in main chunk
        [C]: in function 'require'
        /Users/augusto/.config/nvim/init.lua:15: in main chunk
```

**Comment by max397574** [comment]
I think you don't use packer for plugins right?
If so I know what the problem is but it will be hard for me to test this out because I use packer.
But can you first confirm that you don't use packer and then I'll try to push a fix asap.

**Comment by augustocdias** [comment]
I do use packer.

**Comment by augustocdias** [comment]
The command that is failing doesn't work during startup, but if I call it after it returns a table.

**Comment by max397574** [comment]
can you try this command
`:lua print(vim.inspect(packer_plugins))`

**Comment by augustocdias** [comment]
nil

**Comment by max397574** [comment]
that's why you get the error.
Because this is how I get the count of the plugins
I'll push a fix in a few seconds. Can you than say if the error still exists?

**Comment by augustocdias** [comment]
Yes it works now. Tks :)
