### ISSUE TITLE
Cursor at top of line when starting nvim.

### ISSUE THREAD

**Issue by m00fin** [startup-nvim/startup.nvim#14]
When opening nvim, the cursor is located at line 1 of the document, thus it is necessary to press `j` once to move down to the first menu item. It would be great if the cursor could instead be located at the first menu item when starting nvim to remove the unnecessary key press.

**Comment by max397574** [comment]
This should be fixed now
can you confirm?

**Comment by m00fin** [comment]
Fixed, thank you very much! :)
