### ISSUE TITLE
Allow redisplaying start screen

### ISSUE THREAD

**Issue by enderger** [startup-nvim/startup.nvim#16]
**Is your feature request related to a problem? Please describe.**
Currently, it is impossible to display the start screen again. This limits the versatility of such a system, as it prevents the usage of it as a quick-access dashboard.

**Describe the solution you'd like**
Remove the check in `startup.display()` to allow users to re-display their start screens.

**Describe alternatives you've considered**
If the check is needed to prevent reloading without cause, moving the lock to those places would probably be wise.

**Comment by enderger** [comment]
I've created a PR which implements this feature.

**Comment by max397574** [comment]
@enderger this should be fixed now
sorry that it took so long
I had a lot of other things to do and it was much more complicated than I thought and there were a lot of edge cases

**Comment by max397574** [comment]
since this is should be fixed I'll close this now
if it doesn't work reopen this issue
