### ISSUE TITLE
Display title even without folding

### ISSUE THREAD

**Issue by enderger** [startup-nvim/startup.nvim#17]
**Is your feature request related to a problem? Please describe.**
When working with sections, it is often convenient to use the title option. However, there is no way to do so without folding the section by default.

**Describe the solution you'd like**
Allowing folded sections to be unfolded

**Describe alternatives you've considered**
Titles being handled separately to section folding, though this disallows unfolded-by-default sections.

**Comment by max397574** [comment]
If you don't want to fold and display a title just make it a section

**Comment by max397574** [comment]
I'll try to implement this though

**Comment by enderger** [comment]
> I'll try to implement this though

Thanks, the main reason to do this is to have sections with titles without having to screw around with padding, having sections which can be folded but aren't by default, and using builtin features to have uniform design.
