### ISSUE TITLE
After last update, it is overwriting a buffer with content

### ISSUE THREAD

**Issue by augustocdias** [startup-nvim/startup.nvim#20]
I use [auto-session](https://github.com/rmagatti/auto-session) and when I session is restored startup.nvim is overwriting a buffer from my session. 

**Checklist**
- [x] Checked if issue already exists
- [x] I'm using the latest startup.nvim version

**To Reproduce**
1. Save a session with some buffer opened
2. Reopen nvim with auto restore on
3. startup will overwrite the content of the buffer

**Expected behavior**
I expect startup to not open in this case

Nvim Version: `NVIM v0.7.0-dev+984-g2870311a3`

**Comment by max397574** [comment]
would it be ok for you if I just made an option to disable startup.nvim when you use `nvim` without arguments @augustocdias ?
because it looks kinda hard to me to check if a session is being restored or not.

**Comment by max397574** [comment]
okay
I added a section to the readme about this
(near the bottom)
can you confirm this work for you @augustocdias ?

**Comment by max397574** [comment]
https://github.com/startup-nvim/startup.nvim#conflicts-with-other-plugins-like-auto-session

**Comment by augustocdias** [comment]
If I do that I have to manually call it when it is supposed to open automatically...

**Comment by max397574** [comment]
it's supposed to open automatically when you start nvim without arguements. And then auto-session opens for you.
There is no way to detect if a session got opened (at least I didn't find any by looking at source code of it)
So I think this is the only way
I'll look at it again when I have holidays and see if I find another way

**Comment by augustocdias** [comment]
Until the last commit this was working fine. I didn't have to do anything.

**Comment by max397574** [comment]
I'm confused
When didn't you have to do anything and when do you now have to do anything?

**Comment by augustocdias** [comment]
Last week I didn't have to do anything. I've updated the plug-in this morning and now I have this issue. 

What I'm complaining here was not an issue last week.

**Comment by max397574** [comment]
yes I got that
but when do you now have to display the startup screen manually?

**Comment by max397574** [comment]
okay
there is no other way than to do it manually because auto-session allows no way to detect if a session got opened
so it overwrites your files or you do it manually

**Comment by max397574** [comment]
There were other problems which existed for a long time and needed to be fixed
this is the disadvantage of it

**Comment by max397574** [comment]
at least for now
I'll look at it when I have more time

**Comment by max397574** [comment]
but with this variable set it no longer overwrites buffers right?

**Comment by augustocdias** [comment]
No. But then I have to open it manually even it is suppose to open (when there's no session and no file opened)
