### ISSUE TITLE
Error when using evil theme

### ISSUE THREAD

**Issue by nico-mayora** [startup-nvim/startup.nvim#30]
**Describe the bug**
When enabling the evil theme, the following error is shown upon opening a new neovim session:
```
                       Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...al/share/nvim/plugged/startup.nvim/lua/startup/utils.lua:557: content: expected table for type=mapping and table or function for type=text, got
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        ...al/share/nvim/plugged/startup.nvim/lua/startup/utils.lua:557: in function 'validate_settings'
        ...cal/share/nvim/plugged/startup.nvim/lua/startup/init.lua:382: in function 'display'
        [string ":lua"]:1: in main chunk
```
This does not happen with the `dashboard` theme.

**Checklist**
- [x] Checked if issue already exists
- [x] I'm using the latest startup.nvim version

**To Reproduce**
1. Add the line `require("startup").setup({theme = "evil"})` to your nvim config.
2. Open a new neovim session. The error is shown on screen.
3. Upon dismissing the error, no startup theme is shown.

**Expected behavior**
The evil theme is shown normally.

**Additional Info**
***Config***
https://github.com/nico-mayora/neovim-config
***Neovim Version***
Latest

**Comment by TheSleepingAssassin** [comment]
Hey! Did you find a fix for this?

**Comment by GiuseppeMP** [comment]
Same problema here.

**Comment by Xithrius** [comment]
I am also having this issue.

**Comment by archelaus** [comment]
This is still broken.

**Comment by JulianH99** [comment]
Same problem here

**Comment by b4kura** [comment]
same issue here, still no fix?

**Comment by archelaus** [comment]
FWIW I've since moved to [alpha-nvim](https://github.com/goolord/alpha-nvim).

**Comment by max397574** [comment]
should be closed by https://github.com/startup-nvim/startup.nvim/pull/46
