### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by s1nistr4** [startup-nvim/startup.nvim#36]
**Describe the bug**
I am copying and pasting fresh from the readme.md file into a stock install of Neovim (with packer, telescope and plenary) and it doesn't work

**Checklist**
- [x] Checked if issue already exists
- [x] I'm using the latest startup.nvim version

**To Reproduce**
1. Install Neovim
2. Install packer, telescope and plenary as clearly defined by the readme
3. Install startup.nvim
4. doesn't work
5. 
**Expected behavior**
for it to work. if there is some config that you have to do then it should be clearly described to the end user in the readme.

** Config**
```
require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use 'nvim-lua/plenary.nvim' 
    use {'nvim-telescope/telescope.nvim', tag = '0.1.1'}
    use {
        "startup-nvim/startup.nvim",
        requires = {"nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim"},
        config = function()
            require"startup".setup()
        end
    }
end)
```

After this I ran PackerClean and PackerInstall

***Neovim Version***
0.8.3

**Comment by max397574** [comment]
you also need to run `PackerCompile` (or just `PackerSync` to combine the three)

**Comment by max397574** [comment]
reopen if the issue still exists
