### ISSUE TITLE
line in dashboard?

### ISSUE THREAD

**Issue by obmutescences** [startup-nvim/startup.nvim#37]
**Describe the bug**
some line in left with dashboard theme
![Snipaste_2023-02-12_17-07-08](https://user-images.githubusercontent.com/29330637/218302307-d88e4219-7197-4b04-97a3-60af51dadf9e.png)
but not in right.
is bug or because of neovim config setting?

**Comment by max397574** [comment]
I'm quite sure this is because of indent blankline
do you perhaps use this plugin?
if so you should disable it on the startup.nvim filetype ( `:set ft`)

**Comment by obmutescences** [comment]
thanks, i`ll check out;
